- op: replace
  path: /spec/rules/0/host
  value: api.staging.example.com
- op: replace
  path: /spec/tls/0/secretName
  value: demo-backend-staging-tls
- op: replace
  path: /spec/tls/0/hosts/0
  value: api.staging.example.com
