apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
spec:
  template:
    spec:
      containers:
        - name: demo-backend
          image: ghcr.io/recmanj/demo-backend:sha-3a33b42
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
spec:
  template:
    spec:
      containers:
        - name: demo-frontend
          image: ghcr.io/recmanj/demo-frontend:sha-b6a3b28
