apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  rules:
    - host: app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - app.example.com
      secretName: demo-frontend-tls
